title: Ricard Dalmau # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Technology & content & education 
  <br><br>
  This is my personal website (working on it...)
  <br><br>
  <a href="https://www.linkedin.com/in/ricarddalmau/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
